### ISSUE TITLE
ModuleNotFoundError: No module named 'jsl'

### ISSUE THREAD

**Issue by tpeyron** [matthiasmiller/javascriptlint#2]
Hi all,

I apologize in advance for my newbie level with this, but I've tried as hard as I could to get it right before opening this issue.

I'm trying to install SublimeLinter-jsl. As written in the instructions, I've donwloaded Javascript lint from this repo, and ran the command as following :

`C:\Users\Tsiory\Desktop\javascriptlint-master>python setup.py build
Traceback (most recent call last):
  File "C:\Users\Tsiory\Desktop\javascriptlint-master\setup.py", line 10, in <module>
    from javascriptlint import version
  File "C:\Users\Tsiory\Desktop\javascriptlint-master\javascriptlint\__init__.py", line 2, in <module>
    from jsl import main
ModuleNotFoundError: No module named 'jsl' `

I've been throught the [troubeshooting guide from SublimeLinter](http://www.sublimelinter.com/en/latest/troubleshooting.html), and activated the debbug mode, and adding the path to jsl. I've also installed jsl with :
`npm install --save jsl`
Which resulted in a different path to add to my Sublimelint paths : C:\Users\Tsiory\AppData\Roaming\npm\jsl.

Here is the result of the command "where jsl" :
`C:\Users\Tsiory\Desktop\javascriptlint-master>where jsl
C:\Users\Tsiory\Desktop\javascriptlint-master\jsl
C:\Users\Tsiory\AppData\Roaming\npm\jsl
C:\Users\Tsiory\AppData\Roaming\npm\jsl.cmd`

What am I doing wrong ?

Thanks in advance,

**Comment by matthiasmiller** [comment]
I had not yet upgraded to Python3. Please grab the latest source and retry.

**Comment by tpeyron** [comment]
Does it mean I have to unistall python3, and install python 2.7 to get it running ?

**Comment by matthiasmiller** [comment]
No. The latest code from GitHub supports Python3.

**Comment by tpeyron** [comment]
Perfect, it went throught. Thank you very much !
