### ISSUE TITLE
Im getting an invalid Syntax Error when trying both build and install commands on Mac

### ISSUE THREAD

**Issue by Jeevesy** [matthiasmiller/javascriptlint#5]
customer@Customers-MacBook-Air Development % python --version
Python 2.7.16
customer@Customers-MacBook-Air Development % python3 --version
Python 3.8.2

customer@Customers-MacBook-Air Development % cd javascriptlint-master
customer@Customers-MacBook-Air javascriptlint-master % python setup.py build
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    from javascriptlint import version
  File "/Users/customer/Documents/Development/javascriptlint-master/javascriptlint/__init__.py", line 2, in <module>
    from .jsl import main
  File "/Users/customer/Documents/Development/javascriptlint-master/javascriptlint/jsl.py", line 172
    raise SystemExit(130) from error
                             ^
SyntaxError: invalid syntax
customer@Customers-MacBook-Air javascriptlint-master %

**Comment by matthiasmiller** [comment]
Please run:

python3 setup.py build

**Comment by Jeevesy** [comment]
that seemed to have allowed it to install, i now also have the package on sublime text but for some reason it doesnt work

**Comment by Jeevesy** [comment]
Disregard, that fixed it.
